### ISSUE TITLE
¿Qué representa la IP 192.168.0.4?

### ISSUE THREAD

**Issue by KrlitosForever** [GiancarloAparicio/Real-Time-Node#1]
Estimados junto con saludar, quisiera saber que representa la IP 192.168.0.4 de las siguientes rutas:

src > public > js > config > config.js
```
const HOST = 'http://192.168.0.4:8000';
```

src > views > env.pug
```
    let host="http://192.168.0.4:8000";

    let metadata={
      //Meta
      siteName : 'Chat-node',                                         //Title
      description: 'Chat create with node/vue',                       //Description
      keyWorlds :'node vue javaScript chat',                          //KeyWorlds
      author:'Ramos Aparicio',                                        //Author
      copyright:'© 2020',                                             //Copyright

    }
```

**Comment by GiancarloAparicio** [comment]
Son variables de entorno, no encontre una manera limpia de conectar PUG con las variables .env, asi que lo puse defrente en el codigo.

Cuando lo subas a production reemplaza host con el host de tu servidor, o en desarrollo con el host que uses.

En mi caso tengo tengo un celular viejo que lo uso de servidor, y por eso puse el ip que tiene mi celular en mi casa
