### ISSUE TITLE
¿Error de estilos?

### ISSUE THREAD

**Issue by KrlitosForever** [GiancarloAparicio/Real-Time-Node#2]
Estimados junto con saludar, quisiera que me orientaran de porque razón no me cargan los estilos.
adjunto captura de pantalla.
![Error CSS](https://user-images.githubusercontent.com/7423579/97809831-38266800-1c4e-11eb-8da3-7a895da59a5a.png)

**Comment by GiancarloAparicio** [comment]
Como te comentaba no encontre una forma limpia de unir las variables .env con pug, en el archivo .env.pug cambiar la variable host por la ip de tu servidor, o si lo estas probando en lugar de 192.168.0.N escribe localhost y los archivos se tomaran de la propia pc o servidor

**Comment by KrlitosForever** [comment]
Seguí tu indicación cambie la ip .env.pug, sin embargo sucede exactamente lo mismo. 
De igual forma lo cambie a localhost y el resultado es el mismo.
