### ISSUE TITLE
¿Error de terminal indefinido?

### ISSUE THREAD

**Issue by KrlitosForever** [GiancarloAparicio/Real-Time-Node#3]
Estimado junto con saludar, al ejecutar el servidor arroja error indefinido,

Adjunto imagen para mayor comprensión.

![Error_terminal](https://user-images.githubusercontent.com/7423579/97811114-2ac1ab80-1c57-11eb-81db-6eab5b8bd5c7.png)

**Comment by GiancarloAparicio** [comment]
Debes instalar typescript de forma global y luego de forma local en tu proyecto.
Despues de eso instalar las dependencias...

**Comment by KrlitosForever** [comment]
Estimado seguí tus indicaciones pero ocurre lo mismo adjunto imagen.

![error](https://user-images.githubusercontent.com/7423579/99332981-20123380-285f-11eb-86ca-5c342cd94af9.png)

Saludos.

**Comment by GiancarloAparicio** [comment]
Yo uso linux para desarrollar y en Linux las rutas se manejan con / en cambio en windows las rutas se manejan con \ , esta tomando la ruta como un archivo y no la reconoce como una ruta, cambia / por \ en las rutas para que funcione en windows aunque claro en Linux dejaria de funcionar, 

Para el tema de css abre la consola del navegador y fijate en que error sale , si es un error 404 hay nuevamente un error por las rutas, tienes que fijarte en como se renderiza la ruta de los archivos, es decir si es localhost:8000/css/main.css

Tambien mira los logs para mas informacion del error, src/app/errors crea una carpeta logs y los detalles de los errores se guardara en un archivo logs-express.log (src/app/errors/logs)

**Comment by KrlitosForever** [comment]
Estimado hice la prueba con Debian y los resultados son los mismos.
No hay css y los errores persisten en la terminal.

![Error](https://user-images.githubusercontent.com/7423579/99547046-d9732500-2995-11eb-8234-790236721a4e.png)

Te invitó a realizar el mismo ejercicio. Monta una maquina virtual y ve si es que te da errores. 
Sin más me despido.

**Comment by GiancarloAparicio** [comment]
Active el manejador de logs por defecto, y actualize para que las rutas sean manejadas directamente por node, ademas de usar el localhost por defecto, Intenta si ahora te da errores y de ser asi mira los logs en (src/app/errors/logs) para ver que error sale

**Comment by KrlitosForever** [comment]
Estimado adjunto LOG de errores que se me generó al hacer la prueba. Te comento que CSS no cargo y los mismos errores de siempre.
De igual forma adjunto log, para vuestra revisión.
[logs-express.log](https://github.com/GiancarloAparicio/Real-Time-Node/files/5590671/logs-express.log)
